### ISSUE TITLE
YボタンのOFF認識処理にバグがあります。

### ISSUE THREAD

**Issue by gtudisk** [kawamataryo/8bitdo_zero2#2]
はじめまして。こんばんは。
Raspberry pi 4Bで8BitDo Zero 2コントローラを使用するために、本パッケージをインストールさせてもらいました。
有用なパッケージを公開して頂きありがとうございます。
eightbitdo_zero2.pyの151行目がself.on_y()となっており、YボタンをOFFしてもOFFと認識されませんでした。
self.off_y()とすることで、意図通りの動作となりましたので、ご連絡いたします。

**Comment by kawamataryo** [comment]
反応が遅れてすいません。

Issueありがとうございます！
修正します！

**Comment by kawamataryo** [comment]
v0.1.3で対応しました。
